In [1]:
import numpy as np

In [7]:
# 파일 불러오기
data = np.loadtxt("../data/movielens-1m/ratings.dat", delimiter="::", dtype=np.int64)

In [8]:
print(data[:5, :])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
(1000209, 4)


## 전체 평균 평점 계산하기

In [9]:
mean_rating_total = data[:, 2].mean()
mean_rating_total

3.581564453029317

## 각 사용자 별 평균 평점 계산하기
- 전체데이터 중 기준으로 삼을 열을 인덱싱하여 전체 데이터에 대한 전체기준열 array로 삼을 것이다.
- 기준으로 삼은 열에서 unique(arr)함수로 중복없는 기준열 array를 만들어 array변수에 따로 담는다.
- 전체 기준열 array == 중복없는 기준열 array 중 특정성분을 조건문으로 하여 마스크를 만든다.
- 그 마스크를 전체데이터의 행의 index에 집어 넣으면, 전체기준열에서 특정성분을 가진 행만을 뽑아낼 수 있다. 
- 열의 index에 넣으면 원하는 열만 뽑아낼 수 있다.

In [13]:
# 사용자 번호 인덱싱
user_ids = np.unique(data[:, 0])
user_ids.shape

(6040,)

In [14]:
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [17]:
# 빈 리스트 생성
mean_rating_by_user_list = []
# 각 사용자 별 평점 구하기
for user_id in user_ids:
#     각 사용자 별 데이터 추출
    data_for_user = data[data[:, 0] == user_id, :]
    #print(data_for_user.shape)
#     평점의 평균을 계산
    mean_rating_for_user = data_for_user[:, 2].mean()
    #print(mean_rating_for_user)
    mean_rating_by_user_list.append([user_id, mean_rating_for_user])

In [18]:
mean_rating_by_user_list[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [20]:
mean_rating_by_user_array = np.array(mean_rating_by_user_list)

In [22]:
print(mean_rating_by_user_array[:5])
print(mean_rating_by_user_array.shape)

[[1.         4.18867925]
 [2.         3.71317829]
 [3.         3.90196078]
 [4.         4.19047619]
 [5.         3.14646465]]
(6040, 2)


In [31]:
np.savetxt("mean_rating_by_user.csv", mean_rating_by_user_array, fmt="%.3f", delimiter=",")

PermissionError: [Errno 13] Permission denied: 'mean_rating_by_user.csv'