## Q1 넘파이 모듈을 np 별칭으로 임포트해라

In [1]:
import numpy as np

## Q2 
다음과 같은 리스트를 이용하여
넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)

In [8]:
myList = np.array(['강아지','원숭이','꽃','45','100'])
print(myList, len(myList), type(myList), myList.shape)

['강아지' '원숭이' '꽃' '45' '100'] 5 <class 'numpy.ndarray'> (5,)


## Q3 
np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

## Q4. 
np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

## Q5. 
Q4의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라

array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])

-------------------------------------  

dtype('float64')

## Q6. 
다음과 같이 넘파이 배열을 생성한 후
1차원 배열로 변경하고 슬라이싱하여라
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])

array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])

## Q7. 
다음과 같은 넘파이 배열을 생성한 후
아이템을 교체하여라
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])