In [201]:
import numpy as np

# Numpy 버전 확인

In [ ]:
np.__version__

## 넘파이 배열 만들기
- np.array(리스트)
- 


In [ ]:
# 문자 넘파이 배열 만들기
color_list = np.array(['빨강', '파랑', '초록'])
color_list
print(color_list.size, len(color_list), color_list.shape)

In [ ]:
# 한개의 넘파이 배열 출력시에는 for 반복문 이용
for i in color_list:
    print(i)

## 넘파이 배열 인덱싱
- 넘파이배열변수[indexNumber]

In [ ]:
n1 = np.array([1, 5, 6, 10, 33])
n1

In [ ]:
n1[0]

In [ ]:
n1[2:]

## 퀴즈
- animal이라는 넘파이 배열 생성
- 구성요소는 동물이름[호랑이, 토끼 곰, 거북이, 펭귄]
- 역순으로 하나씩 출력

In [ ]:
animal = np.array(['호랑이', '토끼', '곰', '거북이', '펭귄'])
animal

In [ ]:
# range(초기, 끝, 스텝)
for i in range(5, 0, -1):
    print(i)

In [ ]:
n = len(animal)
for n in range(n-1, -1, -1):
    print(animal[n])

## 넘파이 배열의 속성
- 넘파이배열변수.shape:구조와 크기
- type(변수):객체의 형태 출력
- 변수.ndim:차원
- 변수.dtype:데이터형

In [ ]:
# 정수 실수 문자열 넘파이 생성
np1 = np.array(['세종대', '건국대', '연세대'])
print(np1.shape, np1.ndim, np1.dtype)

## 형변환

In [32]:
np4 = np.array(['세종대', '이화여대', 34, 2.54])
np4

array(['세종대', '이화여대', '34', '2.54'], dtype='<U4')

In [30]:
a = np.array([1, 3, 5, 36])
print(a, a.dtype)

[ 1  3  5 36] int32


In [31]:
# 정수형 -> 문자형 넘파일 배열
b = a.astype(np.str)
print(b, b.dtype)

['1' '3' '5' '36'] <U11


In [33]:
# 정수형 -> 실수형 넘파일 배열
c = a.astype(float)
print(c, c.dtype)

[ 1.  3.  5. 36.] float64


In [36]:
# 정수 -> 문자형
aa = np.array([2, 45, 24, 66], dtype=np.str)
print(aa, aa.dtype)

['2' '45' '24' '66'] <U2


In [38]:
# 실수 -> 정수형
bb = np.array([2.889, 6.24, 3.0], dtype=int)
print(bb, bb.dtype)

[2 6 3] int32


## 2차원 배열 만들기
- 넘파이배열변수 = np.array([1행...][2행...])
- 각 행의 데이터 갯수가 같아야함.

In [39]:
np2d = np.array([[3, 4, 5], [6, 8 ,10]])
np2d

array([[ 3,  4,  5],
       [ 6,  8, 10]])

In [43]:
print(np2d.shape, np2d.size, np2d.ndim)

(2, 3) 6 2


## 퀴즈
- 2행 3열 넘파이 배열 생성 => int형
- 2행 3열 넘파이 배열의 데이터형을 문자형으로 변경 => np.str

In [44]:
np2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
np2d_1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np2d_2 = np2d_1.astype(np.str)
np2d_2

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

## 2차원 넘파이 배열 생성 후 하나씩 출력

In [46]:
# 행단위
for i in np2d_1:
    print(i)

[1 2 3]
[4 5 6]


In [50]:
# 각각의 원소 출력
for i in np2d_1:
    print('-------')
    for j in i:
        print(j)

-------
1
2
3
-------
4
5
6


In [53]:
np1 = np.zeros(5)
np1

array([0., 0., 0., 0., 0.])

In [54]:
np2 = np.zeros((2, 2))
np2

array([[0., 0.],
       [0., 0.]])

In [55]:
np3 = np.ones(5)
np3

array([1., 1., 1., 1., 1.])

## arange

In [ ]:
# arange : 넘파이 array
np.arange(15)

In [58]:
# 소수 가능
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [64]:
# reshape : 차원 변경 시 사용
# 1~30 1차 배열로 생성 후
# 5행 6열로 생성
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## 퀴즈
- 1~15 로 데이터 값을 갖는 넘파이 배열 3행 5열로 생성

In [72]:
npQ = np.arange(1, 16).reshape(3, 5)
npQ

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [74]:
# 2 -> 1차원으로 변경
# 넘파이배열변수.flatten()
np_result = npQ.flatten()
np_result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
total = 0
for i in range(1, 101):
    total += i
print(total)

5050


In [82]:
print(np.sum([x for x in range(1, 101)]))

5050


## 배열의 연산

In [84]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype=np.float64)

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [85]:
# 두 행렬의 크기가 같으므로 같은 위치의 요소끼리 계산이 가능
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [88]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [89]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [90]:
arr1*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [91]:
arr1**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [96]:
# 행렬의 크기가 다른 경우 => a.dot(b)
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(3, 2)
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [108]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10, 11, 12],[13,14,15,16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
arr2d[:2, 1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [114]:
arr1 = np.arange(1, 11)
arr1[::2]

array([1, 3, 5, 7, 9])

## MATH
### 난수
randn = 정규분포에서 난수 추출

rand = 그냥 난수 추출

In [115]:
arr_random = np.random.randn(5)
arr_random

array([-1.3495077 , -0.10744222,  0.38257525,  0.39439273,  1.38728878])

In [118]:
arr_random2 = np.random.randn(2,2)
arr_random2

array([[ 2.00554518, -0.45797419],
       [-0.18180721, -0.379669  ]])

In [120]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [128]:
# max : 하나의 배열 중에서 최대값 출력
# maximum : 각각의 요소를 비교하며 큰 값을 출력
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.29073739, -0.00897426,  0.33033327, -0.11510278, -1.50842276,
       -2.41880377, -1.16679116, -0.6307809 ])

In [129]:
y

array([ 0.88099851, -0.93875223,  0.16163239,  1.25878726,  0.56954052,
        1.59649015, -0.52120317,  0.49231535])

In [130]:
np.max(x)

0.3303332685072064

In [131]:
np.maximum(x, y)

array([ 0.88099851, -0.00897426,  0.33033327,  1.25878726,  0.56954052,
        1.59649015, -0.52120317,  0.49231535])

In [134]:
ran1 = np.random.randn(5, 4)
ran1

array([[-1.54552901, -2.16283414, -0.48262569,  0.10368598],
       [-1.19496732, -1.29299646,  1.57652873, -0.35019861],
       [ 0.6781484 ,  0.43849431, -0.47708849,  0.6947704 ],
       [ 0.43641251,  0.35950683,  0.45743409, -2.03789921],
       [-0.37398138,  0.50996836, -0.17091372,  0.33882412]])

In [135]:
ran1.sum()

-4.495260288000252

In [136]:
ran1.mean()

-0.22476301440001262

In [137]:
# 각 열의 합
ran1.sum(axis=0)

array([-1.99991679, -2.14786109,  0.90333492, -1.25081732])

In [138]:
# 각 행의 합
ran1.sum(axis=1)

array([-4.08730286, -1.26163366,  1.33432461, -0.78454577,  0.30389739])

In [142]:
# 행으로 합치기, 열로 합치기
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [143]:
arr = np.random.randn(8)
arr

array([-0.02192837,  1.707257  , -0.27836793,  1.27730883, -0.05533303,
       -0.86749563,  0.34781587,  1.37754967])

In [144]:
np.sort(arr)

array([-0.86749563, -0.27836793, -0.05533303, -0.02192837,  0.34781587,
        1.27730883,  1.37754967,  1.707257  ])

In [145]:
np.sort(arr)[::1]

array([-0.86749563, -0.27836793, -0.05533303, -0.02192837,  0.34781587,
        1.27730883,  1.37754967,  1.707257  ])

In [147]:
arr = np.random.randn(5, 4)
arr

array([[ 1.46659339,  0.87463681,  0.6777    ,  0.48059993],
       [-0.49138117,  0.23820006,  0.54981602,  0.36628417],
       [-0.35624352,  0.06677612,  0.0301343 ,  0.30222535],
       [-0.3350001 ,  0.50194305, -0.00878617,  0.22651389],
       [-0.93015648,  0.35587194, -0.78538748, -0.07411433]])

In [148]:
np.sort(arr, axis=1)

array([[ 0.48059993,  0.6777    ,  0.87463681,  1.46659339],
       [-0.49138117,  0.23820006,  0.36628417,  0.54981602],
       [-0.35624352,  0.0301343 ,  0.06677612,  0.30222535],
       [-0.3350001 , -0.00878617,  0.22651389,  0.50194305],
       [-0.93015648, -0.78538748, -0.07411433,  0.35587194]])

In [149]:
names=np.array(['hey', 'judy', 'hey', 'amy', 'amy'])
np.unique(names)

array(['amy', 'hey', 'judy'], dtype='<U4')

In [153]:
# 단위행렬
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [155]:
np.eye(N=3, M=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [156]:
np.eye(4, 7, k=2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [157]:
np.random.uniform(0, 1, 10)

array([0.42054336, 0.2039225 , 0.05854673, 0.51645274, 0.09473239,
       0.1031156 , 0.32796177, 0.57166525, 0.94260604, 0.29932661])

In [158]:
np.random.normal(0, 1, 10)

array([-1.17440157, -0.4585413 ,  1.88396755,  0.58213775,  1.07076024,
       -0.00830761, -0.01874864, -1.12080278,  1.71437244,  1.76765137])

In [159]:
names=np.array(['hey', 'judy', 'hey', 'amy', 'amy', 'Myun'])

In [160]:
names=='judy'

array([False,  True, False, False, False, False])

## QUIZ
상위 5퍼센트 숫자 값 추출


 1. 전체 길이를 구한 후 상위 5프로, 0.05 곱한 후 정수형으로 변환
 
 2. 상위 5프로에 해당하는 인덱스 추출

In [184]:
large_arr = np.random.randn(100)
large_arr

array([ 0.55879277, -1.13976003, -0.88482758,  0.96847738, -0.29116915,
       -1.58799435,  1.16113243,  0.75543248, -0.95040015,  2.15798368,
       -0.48369103, -0.90983313,  0.63801039, -0.32925724, -1.13197615,
        0.64631046, -0.07935026, -1.47063835, -0.25511046,  0.5190418 ,
        0.46492261,  0.71620987,  0.6329197 ,  0.32079108,  0.44924309,
       -0.45820663, -0.73671921, -0.04964513,  0.7724701 ,  0.46825698,
        0.38394132,  0.96821209,  1.56468447, -0.208881  ,  0.3195898 ,
       -0.36055319, -0.24428245, -0.27937895, -0.51188868,  0.37468001,
        1.8889312 , -0.86053196, -1.60429606, -1.80129872, -0.33423225,
       -0.54789772,  1.35189542,  0.12889466,  0.88665077, -0.09911291,
        0.98831408,  0.41456224, -1.01267467, -0.45756518, -1.81296641,
       -0.60312856,  0.56313453,  0.161679  , -0.66797175, -0.05132995,
        0.76885133, -1.46398845, -0.3682773 , -0.15339112, -0.20611191,
       -0.86329282, -0.81170626,  0.27443479, -0.85364676, -1.70

In [185]:
np.sort(large_arr)[::-1]

array([ 2.34795776,  2.15798368,  1.97931351,  1.8889312 ,  1.64510571,
        1.56468447,  1.42796144,  1.35189542,  1.16113243,  0.99535779,
        0.98831408,  0.96847738,  0.96821209,  0.89676929,  0.88665077,
        0.7724701 ,  0.76885133,  0.75543248,  0.71620987,  0.64631046,
        0.63801039,  0.6329197 ,  0.56313453,  0.56262839,  0.55879277,
        0.52224284,  0.5190418 ,  0.46825698,  0.46730852,  0.46492261,
        0.44924309,  0.44827156,  0.41456224,  0.41204801,  0.38536721,
        0.38394132,  0.37468001,  0.36613814,  0.35004604,  0.32079108,
        0.3195898 ,  0.28836956,  0.27443479,  0.25278677,  0.1686219 ,
        0.161679  ,  0.12889466,  0.05675484,  0.05360708, -0.01223577,
       -0.03310004, -0.04964513, -0.05132995, -0.06937171, -0.07935026,
       -0.07973755, -0.09911291, -0.15339112, -0.20171216, -0.20611191,
       -0.208881  , -0.24428245, -0.25511046, -0.27937895, -0.29116915,
       -0.32925724, -0.33423225, -0.36055319, -0.3682773 , -0.38

In [186]:
n = int(len(large_arr)*0.05)
np.sort(large_arr)[::-1][0:n]

array([2.34795776, 2.15798368, 1.97931351, 1.8889312 , 1.64510571])

## 외부파일 불러오기
배열명 = np.loadtxt('파일경로',delimiter='구분자',dtype=데이터형)