In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

In [8]:
data = [6, 7.5, 8, 9, 1]
arr = np.array(data)
print(type(arr), id(arr))
arr.shape

<class 'numpy.ndarray'> 1678279434448


(5,)

리스트를 배열로 변환

shape
1차 배열 : 벡터
2차 배열 : 행렬
3차 배열 : 텐서


reshape : 배열 변환


size: 전체 길이

In [ ]:
myList = ['고양이', '나비', '바람']
np.array(myList)

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2.shape
arr2.size

8

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

zero : 행렬크기 만큼 0으로 초기값 지정
ones : 갯수 정하고 1로 채움
empty : 갯수 정하고 정해지지 않은 초깃값으로 채움